'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CosplaySouls.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0:9876
        '''901000:Bare:0:0
        '''331000:Antiquated Dress:5:1
        '''661000:Armor of Artorias:5:10.5
        '''111000:Armor of the Glorious:0:13.3
        '''161000:Armor of the Sun:10:9
        '''201000:Armor of Thorns:5:10.5
        '''511000:Balder Armor:10:10.9
        '''151000:Black Cleric Robe:5:3.9
        '''71000:Black Iron Armor:5:15.6
        '''321000:Black Knight Armor:5:13
        '''301000:Black Leather Armor:10:3.1
        '''641000:Black Sorcerer Cloak:10:1.8
        '''451000:Brass Armor:5:10.9
        '''51000:Brigand Armor:10:3.1
        '''11000:Catarina Armor:5:11.7
        '''171000:Chain Armor:10:6
        '''701000:C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property armors() As String
            Get
                Return ResourceManager.GetString("armors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1200:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:-1:-1:-1:-1:-1:10:9876:0:9876:0:9876:0:9876:0:9876:0
        '''1201:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:-1:-1:-1:-1:-1:10:9876:0:9876:0:9876:0:9876:0:9876:0
        '''1202:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:-1:-1:-1:-1:-1:10:9876:0:9876:0:9876:0:9876:0:9876:0
        '''1203:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:-1:-1:-1:- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property emptyCosplays() As String
            Get
                Return ResourceManager.GetString("emptyCosplays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 81	
        '''82	
        '''83	
        '''84	
        '''85	
        '''86	
        '''87	
        '''88	
        '''90	
        '''91	
        '''93	
        '''95	
        '''97	
        '''98	
        '''100	
        '''102	
        '''104	
        '''106	
        '''108	
        '''110	
        '''112	
        '''115	
        '''117	
        '''119	
        '''121	
        '''124	
        '''126	
        '''129	
        '''131	
        '''133	
        '''136	
        '''139	
        '''141	
        '''144	
        '''146	
        '''149	
        '''152	
        '''154	
        '''157	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	
        '''160	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property endurance() As String
            Get
                Return ResourceManager.GetString("endurance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:Entity:0
        '''1200:Rat:0.3
        '''1201:Small Rat:0.3
        '''1202:Large Rat:0.3
        '''1203:Snow Rat:0.6
        '''2060:Infested Ghoul:0.4
        '''2230:Stray Demon:0.4
        '''2231:Demon Firesage:0.8
        '''2232:Asylum Demon:0.1
        '''2240:Capra Demon:0.3
        '''2250:Taurus Demon:0.2
        '''2260:Batwing Demon:0.6
        '''2270:Mushroom Parent:0.4
        '''2280:Mushroom Child:0.4
        '''2300:Titanite Demon:0.5
        '''2310:Crow Demon:0.6
        '''2320:Iron Golem:0.5
        '''2330:Demonic Foliage:0.4 
        '''2360:Smough:0.6
        '''2370:Channeler:0.8
        '''2380:Giant Stone Knight:0.4
        '''2390:Darkwraith:0.8
        '''2400:Painting Guardian:0.6
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property entities() As String
            Get
                Return ResourceManager.GetString("entities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0:9876
        '''902000:Bare:0:0
        '''332000:Antiquated Gloves:5:0.6
        '''512000:Balder Gauntlets:10:3.5
        '''72000:Black Iron Gauntlets:5:9.2
        '''322000:Black Knight Gauntlets:5:6
        '''302000:Black Leather Gloves:10:1.8
        '''152000:Black Manchette:5:1.8
        '''642000:Black Sorcerer Gauntlets:10:1
        '''552000:Bracelet of the Great Lord:0:2.8
        '''452000:Brass Gauntlets:5:5.4
        '''52000:Brigand Gauntlets:10:1.8
        '''12000:Catarina Gauntlets:5:6.9
        '''702000:Chester`s Gloves:5:1.5
        '''182000:Cleric Gauntlets:10:7.4
        '''142000:Crimson Gloves:5:0.8
        '''132000:C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gauntlets() As String
            Get
                Return ResourceManager.GetString("gauntlets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0:9876
        '''900000:Bare:0:0
        '''510000:Balder Helm:10:4.2
        '''380000:Big Hat:5:3
        '''70000:Black Iron Helm:5:6
        '''320000:Black Knight Helm:5:5
        '''640000:Black Sorcerer Hat:10:0.7
        '''710000:Bloated Head:0:2.5
        '''720000:Bloated Sorcerer Head:0:2.2
        '''450000:Brass Helm:5:5.1
        '''50000:Brigand Hood:10:1.2
        '''10000:Catarina Helm:5:4.5
        '''170000:Chain Helm:10:3
        '''180000:Cleric Helm:10:4.8
        '''330000:Crown of Dusk:5:0.4
        '''540000:Crown of the Dark Sun:0:3
        '''550000:Crown of the Great Lord:0:3
        '''130000:Crystalline Helm:0:4.2
        '''40000:Dark M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property helmets() As String
            Get
                Return ResourceManager.GetString("helmets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0:9876
        '''903000:Bare:0:0
        '''553000:Anklet of the Great Lord:0:2.8
        '''333000:Antiquated Skirt:5:3
        '''513000:Balder Leggings:10:6.4
        '''73000:Black Iron Leggings:5:9.2
        '''323000:Black Knight Leggings:5:7
        '''303000:Black Leather Boots:10:3
        '''643000:Black Sorcerer Boots:10:1
        '''153000:Black Tights:5:1.8
        '''403000:Blood-Stained Skirt:10:2.5
        '''113000:Boots of the Explorer:0:4
        '''453000:Brass Leggings:5:6.4
        '''53000:Brigand Trousers:10:1.8
        '''13000:Catarina Leggings:5:6.9
        '''173000:Chain Leggings:10:4.6
        '''703000:Chester`s Trous [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property leggings() As String
            Get
                Return ResourceManager.GetString("leggings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property maggotgradiconnochop_0zt_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("maggotgradiconnochop_0zt_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property maggotnobgicon_7r2_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("maggotnobgicon_7r2_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change
        '''-1:None
        '''3000:Soul Arrow
        '''3010:Heavy Soul Arrow
        '''3020:Great Soul Arrow
        '''3030:Great Heavy Soul Arrow
        '''3040:Homing Soulmass
        '''3050:Crystal Homing Soulmass
        '''3060:Soul Spear
        '''3070:Crystal Soul Spear
        '''3100:Magic Weapon
        '''3110:Great Magic Weapon
        '''3120:Crystal Magic Weapon
        '''3300:Magic Shield
        '''3310:Strong Magic Shield
        '''3400:Hidden Weapon
        '''3410:Hidden Body
        '''3500:Cast Light
        '''3510:Hush
        '''3520:Aural Decoy
        '''3530:Repair
        '''3540:Fall Control
        '''3550:Chameleon
        '''3600:Resist Curse
        '''3610:Remedy
        '''3700:White Dragon Bre [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Spells() As String
            Get
                Return ResourceManager.GetString("Spells", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property sunlight_maggot__1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sunlight_maggot__1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1200:560000:1001000:902000:903000:902003:902003:900000:900000:10:5:10:8:16:5:5:5:-8:5:5:-4:-5:10:-1:0:-1:0:-1:0:-1:0:-1:0
        '''1201:560000:1001000:902000:903000:902000:902000:900000:900000:8:5:10:6:14:5:5:5:-11:4:5:-7:-6:10:-1:0:-1:0:-1:0:-1:0:-1:0
        '''1202:560000:1001000:902000:903000:902005:902005:900000:900000:20:5:15:14:24:5:5:5:5:6:6:5:5:9:-1:0:-1:0:-1:0:-1:0:-1:0
        '''1203:560000:251000:542000:543000:902010:902010:900000:900000:20:5:15:16:26:5:5:5:-6:5:5:-4:-5:10:-1:0:-1:0:-1:0:-1:0:-1:0
        '''2060:900000:901000:9020 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property T_H_I_C_C() As String
            Get
                Return ResourceManager.GetString("T_H_I_C_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 400
        '''415
        '''433
        '''451
        '''471
        '''490
        '''511
        '''531
        '''552
        '''573
        '''594
        '''616
        '''638
        '''659
        '''682
        '''698
        '''719
        '''742
        '''767
        '''793
        '''821
        '''849
        '''878
        '''908
        '''938
        '''970
        '''1001
        '''1034
        '''1066
        '''1100
        '''1123
        '''1147
        '''1170
        '''1193
        '''1216
        '''1239
        '''1261
        '''1283
        '''1304
        '''1325
        '''1346
        '''1366
        '''1386
        '''1405
        '''1424
        '''1442
        '''1458
        '''1474
        '''1489
        '''1500
        '''1508
        '''1517
        '''1526
        '''1535
        '''1544
        '''1553
        '''1562
        '''1571
        '''1580
        '''1588
        '''1597
        '''1606
        '''1615
        '''1623
        '''1632
        '''1641
        '''1649
        '''1658
        '''1666
        '''1675
        '''1683
        '''1692
        '''1700
        '''1709
        '''1717
        '''1725
        '''1734
        '''1742
        '''1750
        '''1758
        '''1767
        '''1775
        '''1783
        '''1791
        '''1799
        '''1807
        '''1814
        '''1822
        '''1830
        '''1837 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vitality() As String
            Get
                Return ResourceManager.GetString("vitality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 90000:64
        '''100000:65
        '''100100:68
        '''100200:69
        '''100300:65
        '''100400:70  
        '''100500:70
        '''100600:71
        '''100700:71
        '''100800:74
        '''100900:74
        '''101000:75
        '''101100:82
        '''101200:146
        '''101500:147
        '''101600:148
        '''101900:149
        '''103000:150
        '''103100:151
        '''103200:152
        '''103500:153
        '''103600:154
        '''103900:155
        '''102000:156
        '''9011000:157
        '''104000:158
        '''200000:159
        '''200100:160
        '''200200:161
        '''200500:162
        '''200600:163
        '''200900:164
        '''201000:165
        '''201100:166
        '''201200:167
        '''201500:168
        '''201600:169
        '''201900:170
        '''202000:171
        '''202100:172
        '''202200:173
        '''202500:174
        '''202600:175
        '''202900: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property weaponIndexes() As String
            Get
                Return ResourceManager.GetString("weaponIndexes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0:9876
        '''900000:Bare:0:0
        '''901000:Caestus:15:0.5
        '''902000:Claw:15:1
        '''904000:Dark Hand:0:0.5
        '''903000:Dragon Bone Fist:5:8
        '''811000:Blacksmith Giant Hammer:5:6
        '''810000:Blacksmith Hammer:15:5
        '''812000:Hammer of Vamos:5:5
        '''800000:Club:15:3
        '''801000:Mace:15:4
        '''802000:Morning Star:15:4
        '''804000:Pickaxe:15:5
        '''809000:Reinforced Club:15:4
        '''803000:Warpick:15:3.5
        '''852000:Demon&apos;s Great Hammer:15:22
        '''854000:Dragon Tooth:5:18
        '''851000:Grant:5:24
        '''850000:Great Club:15:12
        '''855000:Large Club:15:11
        '''856000:Smough&apos;s Ha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property weapons() As String
            Get
                Return ResourceManager.GetString("weapons", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
