'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsFormApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0
        '''901000:Bare:0
        '''331000:Antiquated Dress:5
        '''661000:Armor of Artorias:5
        '''111000:Armor of the Glorious:0
        '''161000:Armor of the Sun:10
        '''201000:Armor of Thorns:5
        '''511000:Balder Armor:10
        '''151000:Black Cleric Robe:5
        '''71000:Black Iron Armor:5
        '''321000:Black Knight Armor:5
        '''301000:Black Leather Armor:5
        '''641000:Black Sorcerer Cloak:10
        '''451000:Brass Armor:5
        '''51000:Brigand Armor:10
        '''11000:Catarina Armor:5
        '''171000:Chain Armor:10
        '''701000:Chester&apos;s Long Coat:5
        '''181000:Cleric Armor:10
        '''141000:Crimson Robe:5        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property armors() As String
            Get
                Return ResourceManager.GetString("armors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1200:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''1201:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''1202:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''1203:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''2060:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''2230:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:98 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property basicCosplays() As String
            Get
                Return ResourceManager.GetString("basicCosplays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1200:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''1201:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''1202:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''1203:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''2060:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876
        '''2230:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:9876:98 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property emptyCosplays() As String
            Get
                Return ResourceManager.GetString("emptyCosplays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1:81	
        '''2:82	
        '''3:83	
        '''4:84	
        '''5:85	
        '''6:86	
        '''7:87	
        '''8:88	
        '''9:90	
        '''10:91	
        '''11:93	
        '''12:95	
        '''13:97	
        '''14:98	
        '''15:100	
        '''16:102	
        '''17:104	
        '''18:106	
        '''19:108	
        '''20:110	
        '''21:112	
        '''22:115	
        '''23:117	
        '''24:119	
        '''25:121	
        '''26:124	
        '''27:126	
        '''28:129	
        '''29:131	
        '''30:133	
        '''31:136	
        '''32:139	
        '''33:141	
        '''34:144	
        '''35:146	
        '''36:149	
        '''37:152	
        '''38:154	
        '''39:157	
        '''40:160	
        '''41:160	
        '''42:160	
        '''43:160	
        '''44:160	
        '''45:160	
        '''46:160	
        '''47:160	
        '''48:160	
        '''49:160	
        '''50:160	
        '''51:160	
        '''52:160	
        '''53:160	
        '''54:160	
        '''55:160	
        '''56:160	
        '''57:160	
        '''58:160	
        '''59:160	
        '''60:1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property endurance() As String
            Get
                Return ResourceManager.GetString("endurance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:Entity:0
        '''1200:Rat:0.3
        '''1201:Small Rat:0.3
        '''1202:Large Rat:0.3
        '''1203:Snow Rat:0.6
        '''2060:Infested Ghoul:0.4
        '''2230:Stray Demon:0.4
        '''2231:Demon Firesage:0.8
        '''2232:Asylum Demon:0.1
        '''2240:Capra Demon:0.3
        '''2250:Taurus Demon:0.2
        '''2260:Batwing Demon:0.6
        '''2270:Mushroom Parent:0.4
        '''2280:Mushroom Child:0.4
        '''2300:Titanite Demon:0.5
        '''2310:Crow Demon:0.6
        '''2320:Iron Golem:0.5
        '''2330:Demonic Foliage:0.4 
        '''2360:Smough:0.6
        '''2370:Channeler:0.8
        '''2380:Giant Stone Knight:0.4
        '''2390:Darkwraith:0.8
        '''2400:Painting Guardian:0.6
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property entities() As String
            Get
                Return ResourceManager.GetString("entities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0
        '''902000:Bare:0
        '''332000:Antiquated Gloves:5
        '''512000:Balder Gauntlets:10
        '''72000:Black Iron Gauntlets:5
        '''322000:Black Knight Gauntlets:5
        '''302000:Black Leather Gloves:5
        '''152000:Black Manchette:5
        '''642000:Black Sorcerer Gauntlets:10
        '''552000:Bracelet of the Great Lord:0
        '''452000:Brass Gauntlets:5
        '''52000:Brigand Gauntlets:10
        '''12000:Catarina Gauntlets:5
        '''702000:Chester`s Gloves:5
        '''182000:Cleric Gauntlets:10
        '''142000:Crimson Gloves:5
        '''132000:Crystalline Gauntlets:0
        '''42000:Dark Gauntlets:5
        '''402000:Dingy [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gauntlets() As String
            Get
                Return ResourceManager.GetString("gauntlets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0
        '''900000:Bare:0
        '''510000:Balder Helm:10
        '''380000:Big Hat:5
        '''70000:Black Iron Helm:5
        '''320000:Black Knight Helm:5
        '''640000:Black Sorcerer Hat:10
        '''710000:Bloated Head:0
        '''720000:Bloated Sorcerer Head:0
        '''450000:Brass Helm:5
        '''50000:Brigand Hood:10
        '''10000:Catarina Helm:5
        '''170000:Chain Helm:10
        '''180000:Cleric Helm:10
        '''330000:Crown of Dusk:5
        '''540000:Crown of the Dark Sun:0
        '''550000:Crown of the Great Lord:0
        '''130000:Crystalline Helm:0
        '''40000:Dark Mask:5
        '''400000:Dingy Hood:10
        '''1000000:Dragon Head:0
        '''280000: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property helmets() As String
            Get
                Return ResourceManager.GetString("helmets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0
        '''903000:Bare:0
        '''553000:Anklet of the Great Lord:0
        '''333000:Antiquated Skirt:5
        '''513000:Balder Leggings:10
        '''73000:Black Iron Leggings:5
        '''323000:Black Knight Leggings:5
        '''303000:Black Leather Boots:5
        '''643000:Black Sorcerer Boots:10
        '''153000:Black Tights:5
        '''403000:Blood-Stained Skirt:10
        '''113000:Boots of the Explorer:0
        '''453000:Brass Leggings:5
        '''53000:Brigand Trousers:10
        '''13000:Catarina Leggings:5
        '''173000:Chain Leggings:10
        '''703000:Chester`s Trousers:5
        '''183000:Cleric Leggings:10
        '''143000:Crimson Waist [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property leggings() As String
            Get
                Return ResourceManager.GetString("leggings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property maggotgradiconnochop_0zt_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("maggotgradiconnochop_0zt_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property maggotnobgicon_7r2_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("maggotnobgicon_7r2_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property sunlight_maggot__1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sunlight_maggot__1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1:400
        '''2:415
        '''3:433
        '''4:451
        '''5:471
        '''6:490
        '''7:511
        '''8:531
        '''9:552
        '''10:573
        '''11:594
        '''12:616
        '''13:638
        '''14:659
        '''15:682
        '''16:698
        '''17:719
        '''18:742
        '''19:767
        '''20:793
        '''21:821
        '''22:849
        '''23:878
        '''24:908
        '''25:938
        '''26:970
        '''27:1001
        '''28:1034
        '''29:1066
        '''30:1100
        '''31:1123
        '''32:1147
        '''33:1170
        '''34:1193
        '''35:1216
        '''36:1239
        '''37:1261
        '''38:1283
        '''39:1304
        '''40:1325
        '''41:1346
        '''42:1366
        '''43:1386
        '''44:1405
        '''45:1424
        '''46:1442
        '''47:1458
        '''48:1474
        '''49:1489
        '''50:1500
        '''51:1508
        '''52:1517
        '''53:1526
        '''54:1535
        '''55:1544
        '''56:1553
        '''57:1562
        '''58:1571
        '''59:1580
        '''60:1588
        '''61:1597 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vitality() As String
            Get
                Return ResourceManager.GetString("vitality", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:No Change:0
        '''900000:Bare:0
        '''901000:Caestus:15
        '''902000:Claw:15
        '''904000:Dark Hand:0
        '''903000:Dragon Bone Fist:5
        '''811000:Blacksmith Giant Hammer:5
        '''810000:Blacksmith Hammer:15
        '''812000:Hammer of Vamos:5
        '''800000:Club:15
        '''801000:Mace:15
        '''802000:Morning Star:15
        '''804000:Pickaxe:15
        '''809000:Reinforced Club:15
        '''803000:Warpick:15
        '''852000:Demon&apos;s Great Hammer:15
        '''854000:Dragon Tooth:5
        '''851000:Grant:5
        '''850000:Great Club:15
        '''855000:Large Club:15
        '''856000:Smough&apos;s Hammer:5
        '''701000:Battle Axe:15
        '''703000:Butcher Knife:15        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property weapons() As String
            Get
                Return ResourceManager.GetString("weapons", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
