'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsFormApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0:Bare
        '''9876:No Change
        '''331000:Antiquated Dress
        '''661000:Armor of Artorias
        '''111000:Armor of the Glorious
        '''161000:Armor of the Sun
        '''201000:Armor of Thorns
        '''511000:Balder Armor
        '''151000:Black Cleric Robe
        '''71000:Black Iron Armor
        '''321000:Black Knight Armor
        '''301000:Black Leather Armor
        '''641000:Black Sorcerer Cloak
        '''451000:Brass Armor
        '''51000:Brigand Armor
        '''11000:Catarina Armor
        '''171000:Chain Armor
        '''701000:Chester&apos;s Long Coat
        '''181000:Cleric Armor
        '''141000:Crimson Robe
        '''131000:Crystalline Armor
        '''41000:Dark Armor
        '''401000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property armors() As String
            Get
                Return ResourceManager.GetString("armors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1200:9876:9876:9876:9876:9876:9876:9876:9876
        '''1201:9876:9876:9876:9876:9876:9876:9876:9876
        '''1202:9876:9876:9876:9876:9876:9876:9876:9876
        '''1203:9876:9876:9876:9876:9876:9876:9876:9876
        '''2060:9876:9876:9876:9876:9876:9876:9876:9876
        '''2230:9876:9876:9876:9876:9876:9876:9876:9876
        '''2231:9876:9876:9876:9876:9876:9876:9876:9876
        '''2232:9876:9876:9876:9876:9876:9876:9876:9876
        '''2240:9876:9876:9876:9876:9876:9876:9876:9876
        '''2250:9876:9876:9876:9876:9876:9876:9876:9876
        '''2260:9876:9876:9876:9876:9876:9876:9876:9876
        '''2270:9 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property cosplays() As String
            Get
                Return ResourceManager.GetString("cosplays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9876:Entity
        '''1200:Rat
        '''1201:Small Rat
        '''1202:Large Rat
        '''1203:Snow Rat
        '''2060:Infested Ghoul
        '''2230:Stray Demon
        '''2231:Demon Firesage
        '''2232:Asylum Demon
        '''2240:Capra Demon
        '''2250:Taurus Demon
        '''2260:Batwing Demon
        '''2270:Mushroom Parent
        '''2280:Mushroom Child
        '''2300:Titanite Demon
        '''2310:Crow Demon
        '''2320:Iron Golem
        '''2330:Demonic Foliage 
        '''2360:Smough
        '''2370:Channeler
        '''2380:Giant Stone Knight
        '''2390:Darkwraith
        '''2400:Painting Guardian
        '''2410:Silver Knight
        '''2430:Demonic Statue
        '''2500:Hollow
        '''2510:Undead Merchant
        '''2520:Undead As [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property entities() As String
            Get
                Return ResourceManager.GetString("entities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0:Bare
        '''9876:No Change
        '''332000:Antiquated Gloves
        '''512000:Balder Gauntlets
        '''72000:Black Iron Gauntlets
        '''322000:Black Knight Gauntlets
        '''302000:Black Leather Gloves
        '''152000:Black Manchette
        '''642000:Black Sorcerer Gauntlets
        '''552000:Bracelet of the Great Lord
        '''452000:Brass Gauntlets
        '''52000:Brigand Gauntlets
        '''12000:Catarina Gauntlets
        '''702000:Chester`s Gloves
        '''182000:Cleric Gauntlets
        '''142000:Crimson Gloves
        '''132000:Crystalline Gauntlets
        '''42000:Dark Gauntlets
        '''402000:Dingy Gloves
        '''282000:Eastern Gauntlets
        '''652000:Eli [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gauntlets() As String
            Get
                Return ResourceManager.GetString("gauntlets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0:Bare
        '''9876:No Change
        '''510000:Balder Helm
        '''380000:Big Hat
        '''70000:Black Iron Helm
        '''320000:Black Knight Helm
        '''640000:Black Sorcerer Hat
        '''710000:Bloated Head
        '''720000:Bloated Sorcerer Head
        '''450000:Brass Helm
        '''50000:Brigand Hood
        '''10000:Catarina Helm
        '''170000:Chain Helm
        '''180000:Cleric Helm
        '''330000:Crown of Dusk
        '''540000:Crown of the Dark Sun
        '''550000:Crown of the Great Lord
        '''130000:Crystalline Helm
        '''40000:Dark Mask
        '''400000:Dingy Hood
        '''280000:Eastern Helm
        '''650000:Elite Cleric Helm
        '''350000:Elite Knight Helm
        '''620000:F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property helmets() As String
            Get
                Return ResourceManager.GetString("helmets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0:Bare
        '''9876:No Change
        '''553000:Anklet of the Great Lord
        '''333000:Antiquated Skirt
        '''513000:Balder Leggings
        '''73000:Black Iron Leggings
        '''323000:Black Knight Leggings
        '''303000:Black Leather Boots
        '''643000:Black Sorcerer Boots
        '''153000:Black Tights
        '''403000:Blood-Stained Skirt
        '''113000:Boots of the Explorer
        '''453000:Brass Leggings
        '''53000:Brigand Trousers
        '''13000:Catarina Leggings
        '''173000:Chain Leggings
        '''703000:Chester`s Trousers
        '''183000:Cleric Leggings
        '''143000:Crimson Waistcloth
        '''133000:Crystalline Leggings
        '''43000:Dark  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property leggings() As String
            Get
                Return ResourceManager.GetString("leggings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property sunlight_maggot__1_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sunlight_maggot__1_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0:Bare
        '''9876:No Change
        '''901000:Caestus
        '''902000:Claw
        '''904000:Dark Hand
        '''903000:Dragon Bone Fist
        '''811000:Blacksmith Giant Hammer
        '''810000:Blacksmith Hammer
        '''812000:Hammer of Vamos
        '''800000:Club
        '''801000:Mace
        '''802000:Morning Star
        '''804000:Pickaxe
        '''809000:Reinforced Club
        '''803000:Warpick
        '''852000:Demon&apos;s Great Hammer
        '''854000:Dragon Tooth
        '''851000:Grant
        '''850000:Great Club
        '''855000:Large Club
        '''856000:Smough&apos;s Hammer
        '''701000:Battle Axe
        '''703000:Butcher Knife
        '''702000:Crescent Axe
        '''705000:Gargoyle Tail Axe
        '''704000:Golem Axe        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property weapons() As String
            Get
                Return ResourceManager.GetString("weapons", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
